repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
# https://stackoverflow.com/questions/71657355/run-mypy-from-pre-commit-for-different-directories
# - repo: https://github.com/RobertCraigie/pyright-python
#   rev: v1.1.364
#   hooks:
#     - id: pyright